### ISSUE TITLE
Cannot install on Laravel 9

### ISSUE THREAD

**Issue by entity** [RobertBoes/sidecar-inertia-vite#1]
Hey pal,

A huge thank you for making this package seeing as Sidecar Inertia still hasn't been merged to support Vite.

Upon installing I get the following:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires robertboes/sidecar-inertia-vite ^0.1.0@alpha -> satisfiable by robertboes/sidecar-inertia-vite[v0.1.0-alpha].
    - robertboes/sidecar-inertia-vite v0.1.0-alpha requires illuminate/support ^9.43 -> found illuminate/support[v9.43.0, 9.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require robertboes/sidecar-inertia-vite:*" to figure out if any version is installable, or "composer require robertboes/sidecar-inertia-vite:^2.1" if you know which you need.

```

**Comment by entity** [comment]
Ah updating Laravel solved it, nice

**Comment by RobertBoes** [comment]
Yeah sorry, I do need to do some cleanups, I just initialized the package with all latest versions so it has `^9.43` as a requirement. Will update that to `^9` soon-ish 👍

**Comment by entity** [comment]
I thought let's try a simple Laravel upgrade, and it solved it.

Thanks for the reply though @RobertBoes, and again appreciate that you've made this package.

Will share it around as I know others wanting this too
