### ISSUE TITLE
Lambda Execution Exception for RobertBoes\SidecarInertiaVite\SSRFunction: "document is not defined.

### ISSUE THREAD

**Issue by dotsoftwarenl** [RobertBoes/sidecar-inertia-vite#8]
Hello!

We are encountering a new issue when trying to run a SSR page on a local machine.

Lambda Execution Exception for RobertBoes\SidecarInertiaVite\SSRFunction: "document is not defined. [TRACE] ReferenceError: document is not defined at Object.249 (file:///var/task/910.index.mjs:2428:13) at __nccwpck_require__ (file:///var/task/index.mjs:60625:42)".

We have ran the following commands:

npx vite build --ssr
php artisan sidecar:deploy --activate

When deploying to a live environment, with Laravel Vapor, this issue does not occur.

**Comment by RobertBoes** [comment]
That looks like you're using `document` in your script somewhere. SSR runs within node, there is no document/window, so you'd need to account for that

**Comment by dotsoftwarenl** [comment]
Wow, thanks for the quick reply!

I am searching through my project, but it seems that no "document" is used. This only occurs on compiled files such as:

910.index.mjs
index.mjs
app-xxxxxxxx.js
Navbar-xxxxxxx.js

The exception is thrown at @inertiaHead, it might be breaking it there?

![Screenshot 2024-10-03 at 12 07 40](https://github.com/user-attachments/assets/ad532696-caf1-4091-9880-db0bb45e5b60)

It is weird, because it works like a charm when deploying it to my production environment.

**Comment by RobertBoes** [comment]
Could be external packages that aren't SSR-compatible

As for it working on Vapor, does that mean this runs on Vapor and SSR is enabled? If it's not enabled, then it wouldn't go through the entire SSR stack, so it wouldn't throw the error either

**Comment by dotsoftwarenl** [comment]
That seems correct, SSR is not enabled on the live environment, due the fact the page does not load with JavaScript disabled via chrome. Is there any way to check which package is not SSR-compatible?

**Comment by dotsoftwarenl** [comment]
I have found the issue, flowbite was interfering with the SSR functionality. Thanks for digging deeper into this issue!
